### ISSUE TITLE
Could not install into project

### ISSUE THREAD

**Issue by dio-el-claire** [willviles/ember-leaflet-heatmap#3]
Got the following error: The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.
You can add empty `normalizeEntityName` method into blueprint to solve this problem

**Comment by willviles** [comment]
Thanks! 👍 Completed in commit [8e1384e](https://github.com/willviles/ember-leaflet-heatmap/commit/8e1384ec6daac6d4f0b1476404401911df3ea20b) and addon bumped to `0.2.2`.
