### ISSUE TITLE
Point culling weirdness

### ISSUE THREAD

**Issue by brlodi** [willviles/ember-leaflet-heatmap#4]
Currently, points outside the map bounds are not rendered thanks to a check 
[here](https://github.com/willviles/ember-leaflet-heatmap/blob/master/addon/layers/heatmap-layer.js#L121). This makes sense, since it would be silly to draw points the user can't see, but it interacts poorly when scaling is enabled and "weighty" points leave the boundary. These two screenshots demonstrate the effect:

<img width="856" alt="screen shot 2017-06-06 at 10 53 28 pm" src="https://user-images.githubusercontent.com/4230591/26861699-41993f92-4b0b-11e7-8f7f-deb095f5f903.png">
<img width="852" alt="screen shot 2017-06-06 at 10 53 42 pm" src="https://user-images.githubusercontent.com/4230591/26861700-4199c0d4-4b0b-11e7-8589-1b219d6f8f0b.png">

As the user pans the overall shape of the heatmap suddenly changes, because the point and its heatmap contribution are removed while a significant part of its radius is still in view.

I believe this could be remedied by adding a call to `pad()` [again here](https://github.com/willviles/ember-leaflet-heatmap/blob/master/addon/layers/heatmap-layer.js#L121) with a value equal to the calculated radius. That way points would only be removed once they stop contributing to the visible heatmap, rather than as soon as their center leaves the map bounds. Most of the performance gains would be maintained, but with fewer visual artifacts.

**Comment by willviles** [comment]
Good write up, thanks @brlodi! 

If you're able to test & submit a PR then that'd be great as I won't get a chance to look at this in the next week or so.

**Comment by willviles** [comment]
@brlodi, I've just published 0.2.3 which contains your PR! 👍

**Comment by brlodi** [comment]
Awesome! Always feels nice to fix issues upstream. Thanks for the prompt response!
